import {json,sorted} from './recordings.mjs';

export function playerHTML(log){
  const payload=json(log).replaceAll('<','\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>Harmonia Canton demonstrations</title></head><body><noscript>This interactive recording requires JavaScript. Read <a href="evidence.html">the complete static evidence</a> instead.</noscript><script id="event-log" type="application/json">${payload}</script><script>(()=>{const log=JSON.parse(document.getElementById('event-log').textContent);for(const a of log.presentation.styles){const style=document.createElement('style');style.textContent=a.contents;document.head.appendChild(style);}document.body.insertAdjacentHTML('beforeend',log.presentation.shell);for(const image of document.querySelectorAll('img[data-image]'))image.src=log.presentation.images[image.dataset.image];for(const a of log.presentation.scripts){const script=document.createElement('script');script.textContent=a.contents;document.body.appendChild(script);}})();</script></body></html>\n`;
}

export function openerHTML(){
  // Same renderer as index.html; a saved JSON log supplies its complete presentation.
  const renderer=playerHTML.toString().replaceAll('</script>','<\\/script>');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Open a Harmonia recording</title><style>body{margin:0;background:#edf0f4;color:#172638;font:17px/1.5 system-ui}main{max-width:540px;margin:15vh auto;padding:32px;background:white;border-radius:18px}h1{font-size:28px}input{max-width:100%;font:inherit;padding:16px 0}input::file-selector-button{padding:12px 18px;background:#275ee3;color:white;border:0;border-radius:10px;cursor:pointer}input::file-selector-button:hover{background:#1746b5}#error{color:#8a4b13}</style><main><h1>Open a saved demonstration.</h1><p>Choose the exported event log. Its inputs, results, diagrams and selected step travel together.</p><input id="recording-file" type="file" accept=".json,application/json" aria-label="Open exported Harmonia event log"><p id="error" role="alert"></p></main><script>const sorted=${sorted.toString()};const json=${json.toString()};${renderer};document.getElementById('recording-file').addEventListener('change',async event=>{try{const log=JSON.parse(await event.target.files[0].text());if(log.format!=='harmonia-event-log/1'||log.mode!=='recorded')throw Error('Choose a Harmonia event log, version 1.');const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('');if(await digest(json({...log,cursor:null,content_sha256:null}))!==log.content_sha256)throw Error('The saved event log has changed.');for(const a of [...log.presentation.styles,...log.presentation.scripts])if(await digest(a.contents)!==a.sha256)throw Error('A saved renderer asset has changed.');if(await digest(log.presentation.shell)!==log.presentation.sha256)throw Error('The saved presentation has changed.');const html=playerHTML(log);history.replaceState(null,'',location.pathname);document.open();document.write(html);document.close();}catch(error){document.getElementById('error').textContent=error.message;}});</script></html>`;
}
