"""The operator and integration prototypes share the book's appearance and URL contract."""
from pages import shell


def application():
    body = '''<main id="main" class="content"><p class="eyebrow">Workspace simulation · financing-001</p><h1>Property purchase</h1><p class="lead">Review a financing decision, then follow the next person's task.</p><div class="task-context" data-interactive><label>View as<select id="actor"><option>Bank</option><option>Buyer</option><option>Seller</option></select></label><p class="note">Sample roles, not a signed-in identity.<br>This simplified task flow is separate from Alice's recorded four-person story.</p></div><nav class="mode-tabs" aria-label="Workflow view" data-interactive><button data-view="overview">Current task</button><button data-view="history">Activity</button><button data-view="applications">Applications</button></nav>
<section class="mode-panel" data-mode="overview"><div class="task-card" aria-live="polite"><p class="eyebrow" id="action-context">The bank's next action</p><h2 id="action-title">Review financing</h2><p id="action-description">Review the assessment in the financing application.</p><p class="task-status" id="action-notice"></p><div class="task-actions" data-interactive><button class="primary" id="advance-workflow">Approve financing</button><button id="reject-workflow">Refuse financing</button><button id="handoff-workflow" hidden>View the next person's task →</button></div><p class="next-owner" id="next-owner">After approval, the buyer can prepare the offer.</p></div><details id="workflow-progress" data-disclosure><summary>Where this task sits in the workflow</summary><ol class="progress-list"><li data-progress="2">1. Financing decision</li><li data-progress="3">2. Create offer</li><li data-progress="4">3. Review offer</li><li data-progress="5">4. Complete</li></ol><p class="note">Illustrative sequential tasks. The recorded purchase chapter demonstrates proposal relay and receipt separately.</p></details></section>
<section class="mode-panel prose" data-mode="history"><h2>Activity in this simulation</h2><p>These entries are reconstructed from the URL's sample state. They are not ledger receipts.</p><ol id="workflow-history"><li>Buyer submitted evidence.</li></ol><button data-view="overview">Return to the current task →</button></section>
<section class="mode-panel prose" data-mode="applications"><h2>The applications retain their rules.</h2><table><thead><tr><th>Application</th><th>Authority</th><th>Responsibility</th></tr></thead><tbody><tr><td>Financing</td><td>Bank</td><td>Assess the buyer's financing</td></tr><tr><td>Property offers</td><td>Buyer and seller</td><td>Create and review an offer</td></tr></tbody></table><a href="application-builder.html">Explore connecting an application →</a></section>
<details id="connection-states" data-disclosure data-interactive><summary>Explore connection states</summary><label>Observed connection or submission state<select id="simulation-state"><option value="ready">Ready to act</option><option value="pending">Submission pending</option><option value="refused">Source action refused</option><option value="stale">State changed elsewhere</option><option value="disconnected">Connection unavailable</option><option value="rejected">Financing refused</option></select></label><button id="reset-workflow">Start the sample again</button></details><p class="prototype-note">Design simulation. No ledger commands are submitted. <a href="chapters/03-financing-to-offer.html?view=try">Explore a real recorded ledger run →</a></p></main>'''
    return shell('Property purchase', body, slug='application', kind='workspace')


def builder():
    body = '''<main id="main" class="content"><p class="eyebrow">Integration simulation</p><h1>Connect an application</h1><p class="lead">Keep your application's rules. Connect one eligible action to a shared workflow.</p><ol class="progress-list" aria-label="Integration steps"><li data-phase="1">1. Select</li><li data-phase="2">2. Inspect</li><li data-phase="3">3. Map</li><li data-phase="4">4. Build &amp; export</li></ol><label data-interactive>Sample application<select id="sample-package"><option value="legacy">Existing financing application</option><option value="unsupported">Application with nested arguments</option></select></label><section class="task-card" style="margin-top:24px" aria-live="polite"><p class="eyebrow" id="builder-stage">Step 1 of 4</p><h2 id="builder-title">Start with one application</h2><p id="builder-result">Explore a documented sample archive and its approval action.</p><div class="task-actions" data-interactive><button id="builder-back">← Previous</button><button class="primary" id="inspect-sample">Inspect the sample →</button></div><a id="builder-complete" href="chapters/05-bring-an-application.html?view=evidence" hidden>Continue with the real integration guide →</a></section><details id="integration-paths" data-disclosure><summary>Which integration path fits my application?</summary><h3>Direct interface</h3><p>The application implements the shared action interface itself.</p><h3>Generated adapter</h3><p>A compiled binding connects a supported choice in an unchanged archive. The adapter still invokes the actual source choice under its authority.</p></details><p class="prototype-note">Design simulation. No archive is uploaded, compiled, exported, or installed. The real integration requires package inspection, a business mapping, compilation, and an independent golden check.</p><p><a href="application.html">← Return to the workspace</a></p></main>'''
    return shell('Connect an application', body, slug='builder', kind='builder')
