import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {browser} from './cdp.mjs';
const b=await browser(process.argv[2]),base=process.argv[3]||'http://127.0.0.1:56202/.artifacts/quiet-export/',checks=[];
const check=(name,value)=>{assert(value,name);checks.push(name);};
const controls="[...document.querySelectorAll('a[href],button,input,select,summary')].filter(n=>n.getClientRects().length).length";
try{
 for(const width of [1280,390]){await b.viewport(width,1100);await b.navigate(new URL('laboratory.html?story=branch-approved&step=1',base).href);await b.until("!!document.getElementById('next')");check('Export playback interaction budget at '+width,await b.evaluate(controls)===2);check('Export playback fits at '+width,await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));await b.screenshot(`design/0.2/quiet-review/exported-recording-${width}.png`);await b.evaluate("document.getElementById('next').click()");await b.until("new URLSearchParams(location.search).get('step')==='2'");check('Exported Next advances one observation at '+width,true);}
 await b.cdp('Emulation.setScriptExecutionDisabled',{value:true});await b.navigate(new URL('source/design/0.2/chapters/01-product.html',base).href);check('Offline prose remains visible without JavaScript',await b.evaluate("document.querySelector('#chapter-read').getClientRects().length>0&&document.querySelector('#chapter-read').textContent.includes('Imagine that a bank')"));check('Offline prose has only two interactions',await b.evaluate(controls)===2);await b.screenshot('design/0.2/quiet-review/static-chapter-390.png');await b.cdp('Emulation.setScriptExecutionDisabled',{value:false});
 await b.navigate(new URL('source/design/0.2/chapters/01-product.html',base).href);await b.until('!!window.HarmoniaView');await b.viewport(900,1200);await b.cdp('Emulation.setEmulatedMedia',{media:'print'});await b.wait(300);check('Print layout fits an A4 content width',await b.evaluate('document.documentElement.getBoundingClientRect().width<=720&&document.body.scrollWidth<=720'));const pdf=await b.cdp('Page.printToPDF',{printBackground:true,preferCSSPageSize:true});await fs.writeFile('design/0.2/quiet-review/product-chapter.pdf',Buffer.from(pdf.data,'base64'));await b.screenshot('design/0.2/quiet-review/printed-chapter.png');await b.cdp('Emulation.setEmulatedMedia',{media:''});
 check('No exported browser errors',b.errors.length===0);await fs.writeFile('docs/0.2/quiet-export.json',JSON.stringify({checks,errors:b.errors},null,2)+'\n');console.log({checks:checks.length,errors:b.errors});
}finally{await b.cdp('Emulation.setScriptExecutionDisabled',{value:false});await b.cdp('Emulation.setEmulatedMedia',{media:''});b.close();}
