// Private participant capabilities are read locally and never written into reports.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {browser} from './cdp.mjs';
const b=await browser(process.argv[2]),sessions=JSON.parse(await fs.readFile(process.argv[3],'utf8')),origin=new URL(sessions.bank).origin;
const directory='design/0.2/quiet-review';const checks=[],pages=[];
const check=(name,value)=>{assert(value,name);checks.push(name);};
const click=s=>b.evaluate(`document.querySelector(${JSON.stringify(s)}).click()`);
const state=()=>b.evaluate("fetch('/api/state',{headers:{Authorization:'Bearer '+sessionStorage.getItem('harmonia-live')}}).then(r=>r.json())");
async function actor(name,query='view=financing') {const u=new URL(sessions[name]);u.search=query;await b.navigate(u.href);await b.until(`document.querySelector('#live-identity')?.textContent.includes(${JSON.stringify(name==='reviewer'?'observer':name==='bank'?'Bank':'Buyer')})&&document.querySelector('#live-connection')?.textContent.includes('Connected')`);}
async function inspect(id,purpose,next,capture=true){await b.wait(180);const labels=await b.evaluate("[...document.querySelectorAll('a[href],button,input:not([type=hidden]),select,textarea,summary,[role=button]')].filter(n=>n.getClientRects().length&&getComputedStyle(n).visibility!=='hidden').map(n=>n.textContent.trim()||n.getAttribute('aria-label')||n.id)");check(id+' has at most two interactions: '+labels.join(' / '),labels.length<=2);check(id+' fits the viewport',await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));if(capture)await b.screenshot(`${directory}/${id}.png`);pages.push({id,purpose,next,labels,screenshot:capture?`${id}.png`:null});}
async function input(id,value){await b.evaluate(`(()=>{const n=document.getElementById(${JSON.stringify(id)});n.value=${JSON.stringify(value)};n.dispatchEvent(new Event('input'));})()`);}
try{
 await b.cdp('Network.enable');await b.cdp('Network.setCacheDisabled',{cacheDisabled:true});await b.viewport(1280,1000);
 check('Product does not mount the book',(await fetch(origin+'/book/')).status===404);
 const local=await fs.readFile('product/web/target/scala-3.3.6/harmonia-web-fastopt/main.js'),served=Buffer.from(await(await fetch(origin+'/main.js')).arrayBuffer());check('Product serves the current compiled browser',createHash('sha256').update(local).digest('hex')===createHash('sha256').update(served).digest('hex'));
 await b.navigate(origin+'/');await b.until("!!document.getElementById('participant-link')||!!document.getElementById('live-identity')");
 await inspect('live-entry','Enter with a private participant link.','Paste the link and enter the workspace.');
 await actor('bank');await inspect('live-bank','Bank reviews its private case.','Approve financing, or choose another task.');
 check('The bank observes its private application',!!(await state()).private_details);if(await b.evaluate("!!document.getElementById('live-approve-financing')"))await click('#live-approve-financing');await b.until("document.querySelector('.scene-title')?.textContent==='Your approval is issued.'||document.querySelector('#live-workflow')?.textContent==='Workflow: complete'");check('Bank approval committed',(await state()).application==='approved');
 await actor('buyer');await b.viewport(390,1000);await b.until("!!document.getElementById('live-publish-approval')||document.querySelector('#live-workflow')?.textContent==='Workflow: complete'");await inspect('live-buyer-390','Buyer has the signed result and may continue.','Use the approval; no private bank data is shown.');check('Buyer has no private application',!(await state()).private_details);if(await b.evaluate("!!document.getElementById('live-publish-approval')"))await click('#live-publish-approval');await b.until("document.querySelector('#live-workflow')?.textContent==='Workflow: complete'");check('Buyer continuation committed',(await state()).workflow==='complete');
 await actor('reviewer');await inspect('live-observer-390','Observer sees shared completion.','Choose the next task.');check('Observer receives no eligible ledger action',(await state()).eligible.length===0);
 await actor('bank','view=evidence');await inspect('live-evidence-390','Read actual submissions and transaction identities.','Return to task selection.');
 await actor('bank','view=workspace');await inspect('live-task-choice-390','Choose shared work or an application integration.','Compose a workflow, or bring an application.');
 await actor('bank','view=composer');await inspect('compose-name-390','Give the workflow a readable name.','Edit the one input, then Continue.');await input('composition-name','A simple financing review');await click('#composition-next');await b.wait(100);await inspect('compose-reference-390','Give this proposal its own identity.','Enter one reference, then Continue.');await input('composition-reference','quiet-review-'+Date.now());await click('#composition-next');await b.wait(100);await inspect('compose-count-390','Choose the number of actions, from one to four.','Enter the count, then Continue.');await click('#composition-next');
 for(let i=0;i<2;i++){
  await b.wait(90);await inspect('compose-action-name-'+i+'-390','Name this one action.','Edit the name, then Continue.',i===0);await click('#composition-next');await b.wait(90);await inspect('compose-role-'+i+'-390','Name the responsibility for this action.','Edit the role, then Continue.',i===0);await click('#composition-next');await b.wait(90);await inspect('compose-actor-'+i+'-390','Assign this action to a participant.','Choose Bank or Buyer.',i===0);await click(i===0?'#composition-first':'#composition-second');await b.wait(90);await inspect('compose-kind-'+i+'-390','Choose what this one action does.','Approve financing or confirm a review.',i===0);await click(i===0?'#composition-first':'#composition-second');
  if(i===0){await b.wait(90);await inspect('compose-integration-390','Choose the supported application interface.','Direct interface or generated adapter.');await click('#composition-first');}
 }
 await b.wait(150);await inspect('compose-review-390','Review the complete proposed handoff before consent.','Review answers or propose the plan.');const address=await b.evaluate('location.href');await b.navigate(address);await b.until("!!document.getElementById('composition-propose')");check('Cold URL restores the complete unsubmitted plan',await b.evaluate("document.querySelector('#composition-editor h1').textContent==='A simple financing review'"));await click('#composition-propose');await b.until("!document.querySelector('#composition-observations').parentElement.hidden&&document.querySelector('#composition-observations').textContent.includes('Awaiting buyer consent')");await inspect('compose-proposed-390','Bank waits for consent to the observed draft.','Cancel this proposal or choose the next task.');
 await actor('buyer','view=composer');await b.until("!!document.querySelector('button[id^=compose-accept]')");await inspect('compose-consent-390','Buyer reviews the exact proposed handoff.','Accept the plan or choose the next task.');await click('button[id^=compose-accept]');await b.until("document.querySelector('.composition-status')?.textContent.includes('In progress')");
 await actor('bank','view=composer');await b.until("!!document.querySelector('button[id^=compose-execute]')");await inspect('compose-execute-390','Bank may execute its assigned financing action.','Execute the action or choose the next task.');await click('button[id^=compose-execute]');await b.until("!document.querySelector('button[id^=compose-execute]')");
 await actor('buyer','view=composer');await b.until("!!document.querySelector('button[id^=compose-execute]')");await click('button[id^=compose-execute]');await b.until("document.querySelector('.composition-status')?.textContent.includes('Complete')");await inspect('compose-complete-390','Both assigned actions have completed on the ledger.','Choose the next task.');check('Consented composition completes on the ledger',true);
 await actor('bank','view=packages');await b.until("!!document.getElementById('builder-local')");await inspect('package-input-390','Choose the application origin.','Upload a DAR or use a verified source.');await click('#builder-local');await inspect('package-upload-390','Supply one compiled application.','Choose the file, then inspect.');await b.evaluate('history.back()');await b.until("!!document.getElementById('builder-remote')");check('Package Back restores the input choice',true);await click('#builder-remote');await inspect('package-source-390','Review the operator-provisioned local source.','Retrieve it or read the next source.');await click('#builder-retrieve');await b.until("!!document.querySelector('button[id^=builder-generate]')");await b.viewport(1280,1000);await inspect('package-inspected','See what the package and reviewed mapping permit.','Generate and compile, or choose another input.');await click('button[id^=builder-generate]');await b.until("!!document.querySelector('button[id^=builder-download]')");await inspect('package-compiled','The compiler produced the mapped integration project.','Download it or choose another input.');
 const packageId=await b.evaluate("document.querySelector('button[id^=builder-download]').id.slice('builder-download-'.length)");const capability=new URL(sessions.bank).hash.slice('#session='.length);const zip=await fetch(origin+'/api/builder/project/'+packageId,{headers:{Authorization:'Bearer '+capability}});const bytes=Buffer.from(await zip.arrayBuffer());check('Compiled project download is a nonempty ZIP',zip.status===200&&bytes.readUInt32LE(0)===0x04034b50&&bytes.length>1000);
 await actor('bank','view=composer&new=1');await b.until("!!document.getElementById('composition-name')");await inspect('compose-new','Start a second proposal after the first has finished.','One name and Continue.');
 await b.cdp('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await b.until("!!document.getElementById('live-refresh')");await inspect('live-recovery','The connection needs attention before further work.','Reconnect.');await b.cdp('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await click('#live-refresh');await b.until("document.querySelector('#live-connection')?.textContent.includes('Connected')");check('Reconnect restores the unfinished page',await b.evaluate("!document.querySelector('#composition-editor').parentElement.hidden"));
 const unexpected=b.errors.filter(e=>!e.includes('ERR_INTERNET_DISCONNECTED'));check('No unexpected browser errors',unexpected.length===0);
 await fs.writeFile('docs/0.2/quiet-live.json',JSON.stringify({scope:'Actual Scala service and Canton ledger; isolated local sandbox',checks,pages,errors:unexpected},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,pages:pages.length,errors:unexpected}));
}finally{await b.cdp('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});b.close();}
