// Uses private, locally provisioned sessions without writing their capabilities into reports.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {browser} from './cdp.mjs';
const b=await browser(process.argv[2]);
const sessions=JSON.parse(await fs.readFile(process.argv[3],'utf8'));
const origin=new URL(sessions.bank).origin;
const directory='design/0.2/reader/review';await fs.mkdir(directory,{recursive:true});
const checks=[];const check=(name,value)=>{assert(value,name);checks.push(name);};
const click=s=>b.evaluate(`document.querySelector(${JSON.stringify(s)}).click()`);
async function participant(actor,query='') {
  const u=new URL(sessions[actor]);u.search=query;await b.navigate(u.href);
  await b.until(`document.querySelector('#live-identity')?.textContent.includes(${JSON.stringify(actor==='reviewer'?'observer':actor==='bank'?'Bank':'Buyer')}) && document.querySelector('#live-connection')?.textContent.includes('Connected')`);
}
const api=()=>b.evaluate(`fetch('/api/state',{headers:{Authorization:'Bearer '+sessionStorage.getItem('harmonia-live')}}).then(r=>r.json())`);
const connected=()=>b.until(`document.querySelector('#live-connection')?.textContent.includes('Connected')`);
try {
  await b.cdp('Network.enable');await b.cdp('Network.setCacheDisabled',{cacheDisabled:true});
  await b.viewport(1280,1000);await participant('bank','view=composer&theme=dark&text=large');
  check('Session entry preserves query navigation and strips the capability',await b.evaluate(`location.hash==='' && location.search.includes('view=composer') && !document.querySelector('#composer').hidden && document.documentElement.dataset.theme==='dark'`));
  await b.evaluate(`const input=document.querySelector('#composition-name');input.value='An unfinished human draft';input.dispatchEvent(new Event('input'));`);
  await click('a[href="?view=financing"]');await b.wait(2200);await click('#open-workspace-evidence');await click('a[href="?view=composer"]');
  check('Polling and navigation preserve the unfinished composition',await b.evaluate(`document.querySelector('#composition-name').value==='An unfinished human draft'`));
  await b.evaluate(`history.back()`);await b.until(`location.search.includes('view=evidence')`);
  await click('#close-workspace-evidence');
  check('Closing the live drawer restores focus to Evidence',await b.evaluate(`!document.querySelector('.reader-drawer').open && document.activeElement.id==='open-workspace-evidence'`));
  check('Browser Back restores the previous workspace task',true);
  await b.evaluate(`const select=document.querySelector('#workspace-theme');select.value='light';select.dispatchEvent(new Event('change'));`);
  await b.evaluate(`const sizeSelect=document.querySelector('#workspace-text');sizeSelect.value='standard';sizeSelect.dispatchEvent(new Event('change'));`);
  await b.screenshot(`${directory}/live-bank.png`);
  const sprite=await fetch(origin+'/assets/illustrations.png');
  check('The real server supplies the approved illustration sprite',sprite.status===200 && sprite.headers.get('content-type').startsWith('image/png'));
  const chrome=await fetch(origin+'/surface.css');
  check('The real server supplies the shared header and drawer CSS',chrome.status===200 && chrome.headers.get('content-type').startsWith('text/css'));
  const bank=await api();check('The bank sees its real private application',bank.actor==='bank'&&!!bank.private_details);
  check('Only the bank approval is offered initially',await b.evaluate(`!!document.querySelector('#live-approve-financing')&&!document.querySelector('#live-publish-approval')`));
  await click('#live-approve-financing');await b.until(`document.querySelector('.scene-title')?.textContent==='Your approval is issued.'`);
  const approved=await api();check('Approval is an observed committed server result',approved.application==='approved'&&approved.jobs.some(j=>j.outcome==='committed'));
  await participant('buyer');await b.until(`!!document.querySelector('#live-publish-approval')`);
  const buyer=await api();check('The buyer receives evidence without private details',buyer.actor==='buyer'&&buyer.evidence_available&&!buyer.private_details&&!buyer.application);
  check('The buyer has no bank approval control',await b.evaluate(`!document.querySelector('#live-approve-financing')`));
  await b.viewport(390,1000);await b.screenshot(`${directory}/live-buyer-mobile.png`);
  check('Live mobile layout fits the viewport',await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));
  await click('#live-publish-approval');await b.until(`document.querySelector('#live-workflow')?.textContent==='Workflow: complete'`);
  const complete=await api();check('The buyer continuation commits on the ledger',complete.workflow==='complete'&&complete.jobs.some(j=>j.outcome==='committed'));
  await b.cdp('Page.reload');await connected();await b.until(`document.querySelector('#live-workflow')?.textContent==='Workflow: complete'`);
  check('Refresh recovers completion without repeating a command',true);
  await participant('reviewer');await b.until(`document.querySelector('#live-workflow')?.textContent==='Workflow: complete'`);
  const reviewer=await api();check('The observer sees shared completion only',reviewer.actor==='reviewer'&&!reviewer.private_details&&!reviewer.application&&reviewer.eligible.length===0);
  check('Waiting roles receive no unusable financing action',await b.evaluate('document.querySelectorAll(".financing-action button").length===0'));
  await b.viewport(1280,1000);await b.screenshot(`${directory}/live-complete.png`);
  await b.navigate(origin+'/book','/book/source/design/0.2/book-overview.html');await b.until(`!!window.HarmoniaView`);
  check('The actual server mounts the designed book',await b.evaluate(`location.pathname.includes('/book/source/design/0.2/book-overview.html')`));
  await b.navigate(origin+'/book/source/design/0.2/chapters/03-financing-to-offer.html?step=5');await b.until(`!!document.querySelector('.harmonia-scene')`);
  check('The mounted book uses the shared compiled renderer',await b.evaluate(`document.querySelector('.scene-title').textContent==='Alice makes her proposal.'`));
  await b.navigate(origin+'/book/source/design/0.2/sandbox.html');await b.until(`!!window.HarmoniaView`);
  check('The book provides a route back to the live workspace',await b.evaluate(`document.querySelector('#live-entry a').pathname==='/'`));
  await click('#live-entry a');await connected();check('Returning from the book retains participant identity',(await api()).actor==='reviewer');
  const blocked=await fetch(origin+'/book/%2e%2e%2fsessions.json');check('Mounted files cannot traverse into private session artifacts',blocked.status===404);
  const svg=await fetch(origin+'/book/source/design/0.2/assets/component-map.svg');
  check('Original SVG is served with an image MIME type',svg.status===200&&svg.headers.get('content-type').startsWith('image/svg+xml'));

  await b.navigate(origin+'/book/source/design/0.2/author.html?passage=proposal-133&companion=diagram');
  await b.until(`document.querySelector('iframe').contentDocument?.querySelector('.workflow-node')`);
  check('The real server permits same-origin book companions',true);
  const framed=await fetch(origin+'/book/source/design/0.2/reviewer.html');
  check('Book framing is limited to this origin',framed.headers.get('content-security-policy').includes("frame-ancestors 'self'"));
  const workspace=await fetch(origin+'/');
  check('The authenticated workspace remains outside frames',workspace.headers.get('content-security-policy').includes("frame-ancestors 'none'"));
  const catalog=await b.evaluate('HarmoniaAtlas.files');
  const {createHash}=await import('node:crypto');
  for(const [file,metadata] of Object.entries(catalog)) {
    const response=await fetch(origin+'/book/source/'+file);
    assert.equal(response.status,200,'Mounted original: '+file);
    assert.equal(createHash('sha256').update(Buffer.from(await response.arrayBuffer())).digest('hex'),metadata.sha256,'Mounted source fingerprint: '+file);
  }
  check('Every catalog source has its exact original in the exported book',true);
  await b.navigate(origin+'/book/source/design/0.2/sandbox.html?task=composer');
  check('The composer story opens the corresponding live task',await b.evaluate(`document.querySelector('#live-entry a').search==='?view=composer'`));
  await participant('bank','view=composer');
  const reference='reader-review-'+Date.now();
  await b.evaluate(`const input=document.querySelector('#composition-reference');input.value=${JSON.stringify(reference)};input.dispatchEvent(new Event('input'));`);
  check('The editable plan uses the shared renderer',await b.evaluate(`document.querySelectorAll('.composition-preview .workflow-node').length===2`));
  await click('.composition-preview [data-node=draft-1]');
  check('Selecting an editable diagram node focuses its step',await b.evaluate(`document.activeElement.id==='composition-step-1'`));
  await click('#composition-propose');await b.until(`document.querySelector('#composition-observations').textContent.includes('Awaiting buyer consent')`);
  check('The bank proposal is observed before execution',await b.evaluate(`document.querySelector('#composition-observations .workflow-node').dataset.state==='pending'`));
  await participant('buyer','view=composer');await b.until(`!!document.querySelector('button[id^="compose-accept"]')||!![...document.querySelectorAll('#composition-observations button')].find(b=>b.textContent==='Accept this plan')`);
  await b.evaluate(`[...document.querySelectorAll('#composition-observations button')].find(b=>b.textContent==='Accept this plan').click()`);
  await b.until(`!!document.querySelector('#composition-observations [data-node=approval][data-state=current]')`);
  check('Buyer consent enables the first assigned action',true);
  await participant('bank','view=composer');await b.until(`!!document.querySelector('#compose-execute-0-0')`);await click('#compose-execute-0-0');
  await b.until(`!!document.querySelector('#composition-observations [data-node=approval][data-state=complete]')`);
  check('Committed approval changes its shared diagram node to complete',true);
  await participant('buyer','view=composer');await b.until(`!!document.querySelector('#compose-execute-0-1')`);await click('#composition-observations [data-node=review]');
  check('Selecting an observed step opens its actual details',await b.evaluate(`document.querySelector('#compose-detail-0-1').open`));
  await click('#compose-execute-0-1');await b.until(`document.querySelectorAll('#composition-observations [data-state=complete]').length===2`);
  check('Both assigned actions complete through real ledger commands',true);
  await b.viewport(390,1100);await b.screenshot(`${directory}/live-composer-mobile.png`);
  check('The live composer fits a mobile viewport',await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));
  await b.viewport(1280,1050);await participant('bank','view=packages');await b.until(`!!document.querySelector('#builder-retrieve')&&!document.querySelector('#builder-retrieve').disabled`);
  await click('#builder-retrieve');await b.until(`!!document.querySelector('#package-builder .workflow-node')`);
  check('Real DAR inspection feeds the package diagram',await b.evaluate(`document.querySelector('#package-builder [data-node=input]').dataset.state==='complete'`));
  await click('#package-builder [data-node=register]');
  check('The registration node explains the separate evaluation boundary',await b.evaluate(`document.querySelector('#package-builder .workflow-caption').textContent.includes('Separate typed registration')`));
  const generate=await b.evaluate(`document.querySelector('button[id^="builder-generate-"]')?.id`);
  if(generate){await click('#'+generate);await b.until(`document.querySelector('#package-builder [data-node=compile]')?.dataset.state==='complete'`);}
  check('A compiler-confirmed adapter is available as a project download',await b.evaluate(`!!document.querySelector('button[id^="builder-download-"]')`));
  await b.screenshot(`${directory}/live-packages.png`);
  await fs.writeFile('docs/0.2/reader-live.json',JSON.stringify({scope:'Actual Scala service, financing handoff, consented composition, package compilation, framed book and exact exported sources',checks,errors:b.errors},null,2)+'\n');
  check('No browser script or CSP errors',b.errors.filter(e=>!e.includes('favicon.ico')).length===0);
  await fs.writeFile('docs/0.2/reader-live.json',JSON.stringify({scope:'Actual Scala service, financing handoff, consented composition, package compilation, framed book and exact exported sources',checks,errors:b.errors},null,2)+'\n');
  console.log(JSON.stringify({checks:checks.length,errors:b.errors}));
} finally {b.close();}
