#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/environment"
source "$HARMONIA_ROOT/scripts/ledger-packages"
for harmonia_package in "${harmonia_base_packages[@]}"; do
  "$HARMONIA_ROOT/scripts/daml" build --package-root "$HARMONIA_ROOT/$harmonia_package"
done
cd "$HARMONIA_ROOT"
sbt --batch 'scene/scalafmtCheck' 'service/scalafmtCheck' 'web/scalafmtCheck' 'service/compile' 'web/fastLinkJS' 'scene/fastLinkJS'
scripts/harmonia generate-bindings product/packages/mappings/financing.md .artifacts/generated-financing
scripts/daml build --package-root product/ledger/composition
