#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/environment"
harmonia_canton="${HARMONIA_CANTON_JAR:-$HOME/.daml/sdk/3.4.11/canton/canton.jar}"
exec "${JAVA_HOME:-/usr}/bin/java" -jar "$harmonia_canton" "$@"
