#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/environment"
"$HARMONIA_ROOT/scripts/build"
"$HARMONIA_ROOT/scripts/daml" test --package-root "$HARMONIA_ROOT/on-ledger/tests"
cd "$HARMONIA_ROOT/off-ledger"
sbt --batch jvm/test
for harmonia_check in packages-check bindings-check check live-check composer-check builder-check boundaries-check portable-check; do
  "$HARMONIA_ROOT/scripts/harmonia" "$harmonia_check"
done
